language: node_js
node_js:
- "10"

branches:
  only:
  - master

addons:
  chrome: stable

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli@latest

install: npm install

script:
- ng lint
- ng test
- ng build --aot --prod --base-href https://aloha2309-dev.herokuapp.com

deploy:
  - provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    project: "aloha-349e8"
    on:
      branch: master
  - provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    project: "aloha-prod-2309"
    on:
      branch: prod
#script:
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then ng build --prod; fi
#  - if [ "$TRAVIS_BRANCH" != "master" ]; then ng build --dev; fi
