language: node_js
node_js:
- "10"

branches:
  only:
  - master

addons:
  chrome: stable

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli@latest

install: npm install

script:
- ng lint
- ng test
- ng build --aot --prod --base-href https://aloha2309-dev.herokuapp.com

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
